### ISSUE TITLE
template to add css

### ISSUE THREAD

**Issue by yaotzin68** [codepb/jquery-template#103]
hi, i use this, to add css to the template, for me its very usefull maybe you want to add to the library
processElements("data-style", template, data, settings, function ($elem, value) {
            $elem.css(applyFormatters($elem, value, "content", settings));
        });

**Comment by codepb** [comment]
I would prefer not to add more specific properties to the template, but this is worth considering as it does provide a way to the .css function. I would prefer the name data-css for it rather than data-style as it is using the css property. If you submit a pull request with that I'll consider adding it.

**Comment by juanpagfe** [comment]
I have just created a solution on #115
