### ISSUE TITLE
Template loading out of order

### ISSUE THREAD

**Issue by nino90** [codepb/jquery-template#71]
Thank you for writing this cool plugin! However, I'm seeing an issue when trying to load the returned JSON in order. This is the return JSON string (condensed for content):
```
{"results":[{"rn":1,"distance":"3","favorite":false},{"rn":2,"distance"
:"4","favorite":false},{"rn":3,"distance":"4","favorite":false},{"rn":4,"distance":"4","favorite"
:false}}
```
You can see they show up in order (rn:1, rn:2, rn:3, etc). However, when the template takes this JSON and loads it, it does it in whatever order it sees fit. I should say that the JSON block is MUCH bigger than the example (I have text data for display, much like a blog). I am also storing the result in a global variable and paginating on the JSON result (so I don't have to hit the server again). I turned off caching because the results can change in the database.

Here is a code snippet:
```
function loadTrialDetails(cacheKey) {
    // Get the JSON for the trial ids to get details of
    data = getSearchParams("",cacheKey);

    // Load template from our templates folder,
    // and populate the data from the trial object.

    $.getJSON("Myendpointthatreturnsjsondata", data, function(jsonData) {

        if (jsonData != undefined) {
            // First let's reset the global variables... and containers
            page = 1;
            trials = jsonData.trials;
            $("#trial_details_container").html("");

            paginateTrialDetails(1, trials);

        } else {
            // When no results are found, we should blank out existing results.
            $("#trial_details_container").loadTemplate("template/warning.html", "");
        }
    });
};

function paginateTrialDetails(thePage, theTrials) {
    $("#trial_details_container").loadTemplate("template/trial_details.html", theTrials, {
        overwriteCache: true,
        paged:true,
        pageNo: thePage,
        elemPerPage: resultsPerPage,
        append:true,
        complete : function(elem) {
            if (isUserLoggedIn()) {
                disableFeatures(false);
            } else {
                disableFeatures(true);
            }
        }
    });

    if (thePage * resultsPerPage > theTrials.length) {
        $("#trial_details_paging").hide();
    }
}
```
Let me know if you need anything else from me, or if you can give me a push in the right direction. I'm working on a deadline and would love some advice. It should be noted that from a flat file, it works fine. It's only when I'm calling from the server.

**Comment by codepb** [comment]
There are a couple of things I notice here that you could change. overwriteCache only refers to the template. Unless the template changes, I would suggest you don't use it. Effectively I believe this setting causes the template to be loaded for every item in the array of data, massively unnecessary overhead.

I believe the reason things are being put in a random order is because the template loads asynchronously. Try setting async: false in the options as well. This will mean that the template loads synchronously, and the results should be in order. This might slow down the template significantly if you are loading everytime, so if this is a problem, then I definitely recommend you set overwriteCache to false so it only loads the template once.

**Comment by nino90** [comment]
Freakin awesome! Didn't see async documented anywhere, so thanks for that. Also nice to know the the caching is only for the template. I missed that the first time around, but it makes sense. Again, great plugin and thanks for the help!!!
